[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DNFC_DEBUG_VERBOSE=true

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

; Build the contents of /data as a LittleFS filesystem image.
board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit NeoPixel@^1.13.0
    adafruit/Adafruit BusIO@^1.17.1
    adafruit/Adafruit PN532@^1.3.4
